### PR TITLE
Remove path patterns

### PR DESCRIPTION
**Pull request by liujed**
These are no longer used by the CLI as of akitasoftware/akita-cli#191.

### CODE REVIEW

**Comment by mgritter** [comment]
These libraries are imported in superstar in several places.

**Comment by mgritter** [comment]
Ah, I see, the linked PR switched to a superstar lib?

**Comment by liujed** [comment]
Yes, this code is being replaced with code elsewhere.

**Review by versilis — APPROVED** [review]
Thanks for the explanation on why this is being removed. LGTM

**Pull request merged**
