### PR TITLE
Enable CircleCI with suggested configuration

### PR DESCRIPTION
**Pull request by mgritter**

### CODE REVIEW

**Review by thatplguy — APPROVED** [review]
It's been a while since I've looked at configuring CircleCI, but this looks good to me.  Thanks for setting it up.

**Comment by liujed** [comment]
My experience with Jenkins is that as soon as you commit a `Jenkinsfile`, it's picked up and takes effect for that PR. I don't see CircleCI running on this PR. Is this expected?

**Comment by mgritter** [comment]
> I've not used CircleCI before, but my experience with Jenkins is that as soon as you commit a `Jenkinsfile`, it's picked up and takes effect for that PR. I don't see CircleCI running on this PR. Is this expected?

I am puzzled about this too.  It is definitely running on the main branch (where I get emailed errors complaining there is no configuration file.)  So I don't know if there is some issue where PRs or branches do not get built because the config file is missing in main.

**Comment by mgritter** [comment]
Success! https://app.circleci.com/pipelines/github/akitasoftware/akita-libs/3/workflows/54f71c4c-139f-4bfc-bc11-097185ee7636/jobs/3

**Pull request merged**
